### ISSUE TITLE
Volume of syringes in graph

### ISSUE THREAD

**Issue by JB-Wolf** [cambiegroup/flowchem#7]
# Question
Where should the syringe volume and Diameter go? The internal diameter has to be passed somehow.

# Conflicts
Diameter influences minimum and maximum pump rate, volume how many experiments can be conducted. However, I don't think this is a vital part for the graph and mainly clutters it, by adding unnecessary information. I feel the same about pump heads.

# Suggestions
## a)
Syringe pumps can be abstracted to active and passive part in the graph, which would enable the syringe and it's diameter and volume to be stated explicitly. 
## b)
This goes in the experimental procedure file, where at some point the whole platform has to be set to be activated.

**Comment by dcambie** [comment]
Both syringe diameter and syringe volume are needed for Elite11 instantiation.
Example below is current approach, essentially it has to be part of the graph.
This is not avoidable as allowed syringe speed etc e.g. depends on the syringe diameter.

```yaml
devices:

    donor:
        Elite11InfuseOnly:
            port: COM11
            diameter: 4.6 mm
            syringe_volume: 1 ml
            address: 0
```
